# Generated by Django 3.1 on 2021-02-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookAppointment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorCategories',
        ),
    ]
