# Generated by Django 3.1 on 2021-02-20 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookAppointment', '0003_doctorcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='d_s_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookAppointment.doctorcategories'),
            preserve_default=False,
        ),
    ]
