# Generated by Django 3.1 on 2021-02-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAppointment', '0004_auto_20210220_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcategories',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
