# Generated by Django 3.1 on 2021-02-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAppointment', '0005_auto_20210222_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcategories',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
