# Generated by Django 3.1 on 2021-03-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210220_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='homeSlidder/')),
            ],
        ),
    ]
