console.log("Connecting Doctor!");

$(document).on('click','ul li',function(){
    $('#filterOption').css('display', '');
    
})
$("[title~='No-date-specified']").on('click',function(){
    $('#dropdown').addClass('show');
    $('.dropdown-menu').addClass('show');
    $("button").attr("aria-expanded","true");
})

/*$('dropdown-menu').on('click',function(){
    $('ul').children().removeClass('active');
    $('li').addClass('selected').siblings().removeClass('selected');
})*/
$(document).on('click','ul li',function() {

    $("[data-sick~='4266534e-9cb2-47e0-ac2f-d47be6028179']").on('click', function () {
        //$('.doc').css('display', 'none');
        $('#adhd').removeClass('doctor_inactive');
        $('#adhd').addClass('doctor_active');
        //$('#renderDoctor').empty();
        //$('#renderDoctor').append('<div class="col-12 col-lg-4" data-bodyid="Male_Front_Mid, Female_Front_Mid" data-itemid="1" data-sickid="symptom_con228">    <div class="doctor">        <img src="https://assets-us-01.kc-usercontent.com:443/3d9c42d1-db86-00e9-5db3-165ae6aabfa6/e000139f-7554-4006-b280-aa8d5e2ebc5d/213074.jpg" alt="" class="doctor__image" style="width:128px;height:128px;object-fit:cover;object-position:top;"><p class="doctor__name">Dr. Tatpong Chit-ua-aree</p><p class="doctor__specialties__title">Specialties</p>        <p class="doctor__specialies__text">Nephrology (Kidney)<br></p><a href="https://www.bumrungrad.com/en/doctors/Tatpong-Chit-ua-aree" style="margin-top: 0.7em;" class="doctor__btnProfile" target="_blank">View Profile</a>        <div class="accordian page-doctor-profile" id="accordianParent">            <div class="accordian--item">                <a href="#accordian-213074" data-toggle="collapse" class="accordian--item--header" onclick="getDoctorScheduleByAPI("213074")">Schedule</a>                <div id="accordian-213074" class="accordian--item--content collapse">                    <div class="doctor__specialty__item">                       <table class="doctor-time" id="table_213074" width="100%" border="0" cellspacing="1" cellpadding="1">                           <thead>                                               <tr>                                                   <th width="15%">Day</th>                                                   <th width="30%">Time</th>                                                   <th width="55%">Location</th>                                               </tr>                                           </thead>                           <tbody>                           </tbody>                       </table>                   </div>                </div>            </div>        </div>        <div class="doctor__action">            <a href="tel:+6620668888" class="doctor__action__btn doctor__action__btn--call">CALL FOR APPOINTMENT</a>            <a href="/en/contact-us/inquiry?doctorid=213074" class="doctor__action__btn doctor__action__btn--inquiry">SEND AN INQUIRY</a>            <a href="{% url \'bappointment\'%}" doctorid="213074" class="doctor__action__btn doctor__action__btn--appointment" id="doctor-button">BOOK APPOINTMENT</a>        </div>    </div></div>');
        //$('#renderDoctor').append('<div class="col-12 col-lg-4" data-bodyid="Male_Front_Mid, Female_Front_Mid" data-itemid="1" data-sickid="symptom_con228">    <div class="doctor">        <img src="https://assets-us-01.kc-usercontent.com:443/3d9c42d1-db86-00e9-5db3-165ae6aabfa6/0fa3300d-054a-4730-82ec-3c74a5b38075/091223.jpg" alt="" class="doctor__image" style="width:128px;height:128px;object-fit:cover;object-position:top;">        <p class="doctor__name">            Assist.Prof.Dr. Krairerk Athirakul        </p>        <p class="doctor__specialties__title">Specialties</p>        <p class="doctor__specialies__text">Internal Medicine<br>Nephrology (Kidney)<br></p>        <a href="https://www.bumrungrad.com/en/doctors/Krairerk-Athirakul" style="margin-top: 0.7em;" class="doctor__btnProfile" target="_blank">View Profile</a>        <div class="accordian page-doctor-profile" id="accordianParent">            <div class="accordian--item">                <a href="#accordian-091223" data-toggle="collapse" class="accordian--item--header" onclick="getDoctorScheduleByAPI("091223")">Schedule</a>                <div id="accordian-091223" class="accordian--item--content collapse">                    <div class="doctor__specialty__item">                       <table class="doctor-time" id="table_091223" width="100%" border="0" cellspacing="1" cellpadding="1">                           <thead>                                               <tr>                                                   <th width="15%">Day</th>                                                   <th width="30%">Time</th>                                                   <th width="55%">Location</th>                                               </tr>                                           </thead>                           <tbody>                           </tbody>                       </table>                   </div>                </div>            </div>        </div>        <div class="doctor__action">            <a href="tel:+6620668888" class="doctor__action__btn doctor__action__btn--call">CALL FOR APPOINTMENT</a>            <a href="/en/contact-us/inquiry?doctorid=091223" class="doctor__action__btn doctor__action__btn--inquiry">SEND AN INQUIRY</a>            <a href="{% url \'bappointment\'%}" doctorid="091223" class="doctor__action__btn doctor__action__btn--appointment">BOOK APPOINTMENT</a>        </div>    </div></div>');
        //$('#renderDoctor').append('<div class="col-12 col-lg-4" data-bodyid="Male_Front_Mid, Female_Front_Mid" data-itemid="1" data-sickid="symptom_con228">    <div class="doctor">        <img src="https://assets-us-01.kc-usercontent.com:443/3d9c42d1-db86-00e9-5db3-165ae6aabfa6/754afd74-409a-444a-a3d9-d5abe2cadc58/256654.jpg" alt="" class="doctor__image" style="width:128px;height:128px;object-fit:cover;object-position:top;">        <p class="doctor__name">            Rear Admiral.Dr. Srivila Phipathananunth        </p>        <p class="doctor__specialties__title">Specialties</p>        <p class="doctor__specialies__text">Nephrology (Kidney)<br></p>        <a href="https://www.bumrungrad.com/en/doctors/Srivila-Phipathananunth" style="margin-top: 0.7em;" class="doctor__btnProfile" target="_blank">View Profile</a>        <div class="accordian page-doctor-profile" id="accordianParent">            <div class="accordian--item">                <a href="#accordian-256654" data-toggle="collapse" class="accordian--item--header" onclick="getDoctorScheduleByAPI("256654")">Schedule</a>                <div id="accordian-256654" class="accordian--item--content collapse">                    <div class="doctor__specialty__item">                       <table class="doctor-time" id="table_256654" width="100%" border="0" cellspacing="1" cellpadding="1">                           <thead>                                               <tr>                                                   <th width="15%">Day</th>                                                   <th width="30%">Time</th>                                                   <th width="55%">Location</th>                                               </tr>                                           </thead>                           <tbody>                           </tbody>                       </table>                   </div>                </div>            </div>        </div>        <div class="doctor__action">            <a href="tel:+6620668888" class="doctor__action__btn doctor__action__btn--call">CALL FOR APPOINTMENT</a>            <a href="/en/contact-us/inquiry?doctorid=256654" class="doctor__action__btn doctor__action__btn--inquiry">SEND AN INQUIRY</a>            <a href="{% url \'bappointment\'%}" doctorid="256654" class="doctor__action__btn doctor__action__btn--appointment">BOOK APPOINTMENT</a>        </div>    </div></div>');
        //$('#renderDoctor').append('<div class="col-12 col-lg-4" data-bodyid="Male_Front_Mid, Female_Front_Mid" data-itemid="1" data-sickid="symptom_con228">    <div class="doctor">        <img src="https://assets-us-01.kc-usercontent.com:443/3d9c42d1-db86-00e9-5db3-165ae6aabfa6/08e04668-8465-4773-bb1b-eebf68a0571a/053119.jpg" alt="" class="doctor__image" style="width:128px;height:128px;object-fit:cover;object-position:top;">        <p class="doctor__name">            Dr. Nopawan Kittivat        </p>        <p class="doctor__specialties__title">Specialties</p>        <p class="doctor__specialies__text">Endocrinology (Diabetes, Thyroid, Hormone, Nutrition)<br></p>        <a href="https://www.bumrungrad.com/en/doctors/Nopawan-Kittivat" style="margin-top: 0.7em;" class="doctor__btnProfile" target="_blank">View Profile</a>        <div class="accordian page-doctor-profile" id="accordianParent">            <div class="accordian--item">                <a href="#accordian-053119" data-toggle="collapse" class="accordian--item--header" onclick="getDoctorScheduleByAPI("053119")">Schedule</a>                <div id="accordian-053119" class="accordian--item--content collapse">                    <div class="doctor__specialty__item">                       <table class="doctor-time" id="table_053119" width="100%" border="0" cellspacing="1" cellpadding="1">                           <thead>                                               <tr>                                                   <th width="15%">Day</th>                                                   <th width="30%">Time</th>                                                   <th width="55%">Location</th>                                               </tr>                                           </thead>                           <tbody>                           </tbody>                       </table>                   </div>                </div>            </div>        </div>        <div class="doctor__action">            <a href="tel:+6620668888" class="doctor__action__btn doctor__action__btn--call">CALL FOR APPOINTMENT</a>            <a href="/en/contact-us/inquiry?doctorid=053119" class="doctor__action__btn doctor__action__btn--inquiry">SEND AN INQUIRY</a>            <a href="{% url \'bappointment\'%}" doctorid="053119" class="doctor__action__btn doctor__action__btn--appointment">BOOK APPOINTMENT</a>        </div>    </div></div>');
    })

    //$('.nano-pane').css('display', '');
})

$(document).on('click','ul li',function(){
        $("[data-sick~='4266534e-9cb2-47e0-ac2f-d47be6028179']").on('click',function(){
            //$('#renderDoctor').empty();
            //$('#renderDoctor').append('<div class="col-12 col-lg-4" data-bodyid="Male_Front_Mid, Female_Front_Mid" data-itemid="1" data-sickid="symptom_sym229">    <div class="doctor">        <img src="https://assets-us-01.kc-usercontent.com:443/3d9c42d1-db86-00e9-5db3-165ae6aabfa6/f6b08ce6-70d6-49e4-a590-9a9c77d5538e/161695.jpg" alt="" class="doctor__image" style="width:128px;height:128px;object-fit:cover;object-position:top;">        <p class="doctor__name">            Dr. Wadchara Pumpradit        </p>        <p class="doctor__specialties__title">Specialties</p>        <p class="doctor__specialies__text">Infectious Disease<br>Internal Medicine<br></p>        <a href="https://www.bumrungrad.com/en/doctors/Wadchara-Pumpradit" style="margin-top: 0.7em;" class="doctor__btnProfile" target="_blank">View Profile</a>        <div class="accordian page-doctor-profile" id="accordianParent">            <div class="accordian--item">                <a href="#accordian-161695" data-toggle="collapse" class="accordian--item--header" onclick="getDoctorScheduleByAPI("161695")">Schedule</a>                <div id="accordian-161695" class="accordian--item--content collapse">                    <div class="doctor__specialty__item">                       <table class="doctor-time" id="table_161695" width="100%" border="0" cellspacing="1" cellpadding="1">                           <thead>                                               <tr>                                                   <th width="15%">Day</th>                                                   <th width="30%">Time</th>                                                   <th width="55%">Location</th>                                               </tr>                                           </thead>                           <tbody>                           </tbody>                       </table>                   </div>                </div>            </div>        </div>        <div class="doctor__action">            <a href="tel:+6620668888" class="doctor__action__btn doctor__action__btn--call">CALL FOR APPOINTMENT</a>            <a href="/en/contact-us/inquiry?doctorid=161695" class="doctor__action__btn doctor__action__btn--inquiry">SEND AN INQUIRY</a>            <a href="{% url \'bappointment\'%}" doctorid="161695" class="doctor__action__btn doctor__action__btn--appointment">BOOK APPOINTMENT</a>        </div>    </div></div>');
            //$('#renderDoctor').append('<div class="col-12 col-lg-4" data-bodyid="Male_Front_Mid, Female_Front_Mid" data-itemid="1" data-sickid="symptom_sym229">    <div class="doctor">        <img src="https://assets-us-01.kc-usercontent.com:443/3d9c42d1-db86-00e9-5db3-165ae6aabfa6/7525840b-60f2-4149-bf11-ca45464e94e8/053394.jpg" alt="" class="doctor__image" style="width:128px;height:128px;object-fit:cover;object-position:top;">        <p class="doctor__name">            Dr. Wiwat Wongsirisak        </p>        <p class="doctor__specialties__title">Specialties</p>        <p class="doctor__specialies__text">Internal Medicine<br></p>        <a href="https://www.bumrungrad.com/en/doctors/Wiwat-Wongsirisak" style="margin-top: 0.7em;" class="doctor__btnProfile" target="_blank">View Profile</a>        <div class="accordian page-doctor-profile" id="accordianParent">            <div class="accordian--item">                <a href="#accordian-053394" data-toggle="collapse" class="accordian--item--header" onclick="getDoctorScheduleByAPI("053394")">Schedule</a>                <div id="accordian-053394" class="accordian--item--content collapse">                    <div class="doctor__specialty__item">                       <table class="doctor-time" id="table_053394" width="100%" border="0" cellspacing="1" cellpadding="1">                           <thead>                                               <tr>                                                   <th width="15%">Day</th>                                                   <th width="30%">Time</th>                                                   <th width="55%">Location</th>                                               </tr>                                           </thead>                           <tbody>                           </tbody>                       </table>                   </div>                </div>            </div>        </div>        <div class="doctor__action">            <a href="tel:+6620668888" class="doctor__action__btn doctor__action__btn--call">CALL FOR APPOINTMENT</a>            <a href="/en/contact-us/inquiry?doctorid=053394" class="doctor__action__btn doctor__action__btn--inquiry">SEND AN INQUIRY</a>            <a href="{% url \'bappointment\'%}" doctorid="053394" class="doctor__action__btn doctor__action__btn--appointment">BOOK APPOINTMENT</a>        </div>    </div></div>');
            //$('#renderDoctor').append('<div class="col-12 col-lg-4" data-bodyid="Male_Front_Mid, Female_Front_Mid" data-itemid="1" data-sickid="symptom_sym229">    <div class="doctor">        <img src="https://assets-us-01.kc-usercontent.com:443/3d9c42d1-db86-00e9-5db3-165ae6aabfa6/f7460a27-3bf9-43f6-8080-017c4a37360a/053054.jpg" alt="" class="doctor__image" style="width:128px;height:128px;object-fit:cover;object-position:top;">        <p class="doctor__name">            Dr. Narendar Malhotra        </p>        <p class="doctor__specialties__title">Specialties</p>        <p class="doctor__specialies__text">Cardiology (Heart)<br>Internal Medicine<br></p>        <a href="https://www.bumrungrad.com/en/doctors/Narendar-Malhotra" style="margin-top: 0.7em;" class="doctor__btnProfile" target="_blank">View Profile</a>        <div class="accordian page-doctor-profile" id="accordianParent">            <div class="accordian--item">                <a href="#accordian-053054" data-toggle="collapse" class="accordian--item--header" onclick="getDoctorScheduleByAPI("053054")">Schedule</a>                <div id="accordian-053054" class="accordian--item--content collapse">                    <div class="doctor__specialty__item">                       <table class="doctor-time" id="table_053054" width="100%" border="0" cellspacing="1" cellpadding="1">                           <thead>                                               <tr>                                                   <th width="15%">Day</th>                                                   <th width="30%">Time</th>                                                   <th width="55%">Location</th>                                               </tr>                                           </thead>                           <tbody>                           </tbody>                       </table>                   </div>                </div>            </div>        </div>        <div class="doctor__action">            <a href="tel:+6620668888" class="doctor__action__btn doctor__action__btn--call">CALL FOR APPOINTMENT</a>            <a href="/en/contact-us/inquiry?doctorid=053054" class="doctor__action__btn doctor__action__btn--inquiry">SEND AN INQUIRY</a>            <a href="{% url \'bappointment\'%}" doctorid="053054" class="doctor__action__btn doctor__action__btn--appointment">BOOK APPOINTMENT</a>        </div>    </div></div>');
            //$('#renderDoctor').append('<div class="col-12 col-lg-4" data-bodyid="Male_Front_Mid, Female_Front_Mid" data-itemid="1" data-sickid="symptom_sym229">    <div class="doctor">        <img src="https://assets-us-01.kc-usercontent.com:443/3d9c42d1-db86-00e9-5db3-165ae6aabfa6/933a773f-cea4-4b2b-bd56-0819256b63eb/080267.jpg" alt="" class="doctor__image" style="width:128px;height:128px;object-fit:cover;object-position:top;">        <p class="doctor__name">            Dr. Pavarat Saengaram        </p>        <p class="doctor__specialties__title">Specialties</p>        <p class="doctor__specialies__text">Internal Medicine<br></p>        <a href="https://www.bumrungrad.com/en/doctors/Pavarat-Saengaram" style="margin-top: 0.7em;" class="doctor__btnProfile" target="_blank">View Profile</a>        <div class="accordian page-doctor-profile" id="accordianParent">            <div class="accordian--item">                <a href="#accordian-080267" data-toggle="collapse" class="accordian--item--header" onclick="getDoctorScheduleByAPI("080267")">Schedule</a>                <div id="accordian-080267" class="accordian--item--content collapse">                    <div class="doctor__specialty__item">                       <table class="doctor-time" id="table_080267" width="100%" border="0" cellspacing="1" cellpadding="1">                           <thead>                                               <tr>                                                   <th width="15%">Day</th>                                                   <th width="30%">Time</th>                                                   <th width="55%">Location</th>                                               </tr>                                           </thead>                           <tbody>                           </tbody>                       </table>                   </div>                </div>            </div>        </div>        <div class="doctor__action">            <a href="tel:+6620668888" class="doctor__action__btn doctor__action__btn--call">CALL FOR APPOINTMENT</a>            <a href="/en/contact-us/inquiry?doctorid=080267" class="doctor__action__btn doctor__action__btn--inquiry">SEND AN INQUIRY</a>            <a href="{% url \'bappointment\'%}" doctorid="080267" class="doctor__action__btn doctor__action__btn--appointment">BOOK APPOINTMENT</a>        </div>    </div></div>');
        })
        
        //$('.nano-pane').css('display', '');
        
    
})

