# Generated by Django 3.1 on 2021-02-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambulance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceSlidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AmbulaceName', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='slidder/')),
            ],
        ),
    ]
