# Generated by Django 3.1 on 2021-02-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ambulance', '0002_ambulanceslidding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulace',
            old_name='Location',
            new_name='location',
        ),
    ]
