# Generated by Django 3.1 on 2021-02-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambulance', '0003_auto_20210222_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulace',
            name='form_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
