# Generated by Django 3.1 on 2021-02-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambulance', '0004_ambulace_form_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulace',
            name='driver_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
