# Generated by Django 3.1 on 2021-02-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ambulance', '0005_auto_20210223_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulace',
            name='form_location',
        ),
    ]
